# app.yaml = application config file
application: pup-dbms-thesis-manager-2
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /css
  static_dir: css

- url: /font-awesome
  static_dir: font-awesome

- url: /img
  static_dir: img

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
